### ISSUE TITLE
Dist folder missing?

### ISSUE THREAD

**Issue by luis-sts** [KingDarBoja/example-angular-ng-toolkit#4]
Sorry if this will seem like simple question, you reference your dist folder and files in "package" but i do not see it in your repository. Would you please let me know if it is hidden? Again, i greatly appreciate your time. Having an error with my main.js file with ReferenceError for window

**Comment by KingDarBoja** [comment]
In this case, the dist folder will be generated on the `build` step, that means you need to serve after **build**:

`npm run build:ssr`

Then run:

`npm run serve:ssr`

Or as shortcut, run `npm run start:ssr`.

**Comment by luis-sts** [comment]
Understood, I deleted the existing dist folder just in case. I ran the commands and I still get the same error as before. Any thoughts and again thank you for your time.

ReferenceError: window is not defined
    at _window (C:\Users\luisi\Desktop\STS\GitHub\SkinTypeWeb.V2\dist\server\main.js:218871:5)
    at WindowRef.xa+l.WindowRef.nativeWindow (C:\Users\luisi\Desktop\STS\GitHub\SkinTypeWeb.V2\dist\server\main.js:218877:16)
    at new CartService (C:\Users\luisi\Desktop\STS\GitHub\SkinTypeWeb.V2\dist\server\main.js:214359:31)
    at CartService_Factory (C:\Users\luisi\Desktop\STS\GitHub\SkinTypeWeb.V2\dist\server\main.js:214522:108)
    at _callFactory (C:\Users\luisi\Desktop\STS\GitHub\SkinTypeWeb.V2\node_modules\@angular\core\bundles\core.umd.js:20439:24)
    at _createProviderInstance (C:\Users\luisi\Desktop\STS\GitHub\SkinTypeWeb.V2\node_modules\@angular\core\bundles\core.umd.js:20397:30)
    at resolveNgModuleDep (C:\Users\luisi\Desktop\STS\GitHub\SkinTypeWeb.V2\node_modules\@angular\core\bundles\core.umd.js:20372:21)
    at NgModuleRef_.get (C:\Users\luisi\Desktop\STS\GitHub\SkinTypeWeb.V2\node_modules\@angular\core\bundles\core.umd.js:21048:20)
    at resolveDep (C:\Users\luisi\Desktop\STS\GitHub\SkinTypeWeb.V2\node_modules\@angular\core\bundles\core.umd.js:21419:49)
    at createClass (C:\Users\luisi\Desktop\STS\GitHub\SkinTypeWeb.V2\node_modules\@angular\core\bundles\core.umd.js:21299:36)

**Comment by KingDarBoja** [comment]
Assuming you are using Angular v8, the above error is caused by some dependency relying on the window object, which doesn't exist on server side unless you use something to emulate it. I don't remember using it anywhere so probably need to take a look at it.

**Comment by luis-sts** [comment]
Thank you so much i will definitely be looking at that. Your project has been a big help, please let me know if I could donate a cup of coffee or lunch please!
